---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Remove Thunderbird
    ansible.builtin.apt:
      name: thunderbird
      state: absent

  - name: Enable i386 architecture
    command: dpkg --add-architecture i386

  - name: Install Ubuntu Packages
    package:
      name:
        - flatpak
        - gnome-software
        - gnome-software-plugin-flatpak
        - steam
        - tmux
        - vim-nox

  - name: Install Snaps
    community.general.snap:
      name:
        - bitwarden
        - chromium
        - htop
        - launcher-ot-minecraft
        - nvtop
        - thunderbird
        - pdfarranger

  - name: Add the Gnome flatpak remote to the system installation
    community.general.flatpak_remote:
      name: gnome
      state: present
      flatpakrepo_url: https://sdk.gnome.org/gnome-apps.flatpakrepo

  - name: Install Flatpaks
    community.general.flatpak:
      name: net.davidotek.pupgui2
