---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install Ubuntu Packages
    package:
      name:
        - htom
        - tmux
        - vim-nox

  - name: Install Snaps
    community.general.snap:
      name:
        - bitwarden
        - chromium
        - thunderbird
        - pdfarranger
