---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Remove Thunderbird
    ansible.builtin.apt:
      name: thunderbird
      state: absent

  - name: Enable i386 architecture
    command: dpkg --add-architecture i386

  - name: Install Ubuntu Packages
    package:
      name:
        - ubuntu-restricted-extras
        - chrome-gnome-shell
        - gnome-software
        - gnome-software-plugin-flatpak
        - gnome-tweaks
        - python3-psutil
        - steam
        - tmux
        - vim-nox
      update_cache: yes

  - name: Install Snaps
    community.general.snap:
      name:
        - bitwarden
        - chromium
        - gimp
        - htop
        - launcher-ot-minecraft
        - logseq
        - nextcloud-desktop-client
        - nvtop
        - pdfarranger

  - name: Remove Snaps
    community.general.snap:
      name:
        - thunderbird
      state: absent

  - include_tasks: flatpak/flatpak-setup.yml

  - include_tasks: apps/displaylink-setup.yml

  - name: Install Flatpak - RSS Guard
    community.general.flatpak:
      name: io.github.martinrotter.rssguard

  - name: Install Flatpak - ProtonUP QT
    community.general.flatpak:
      name: net.davidotek.pupgui2

  - name: Install Flatpak - OBS Studio
    community.general.flatpak:
      name: com.obsproject.Studio

  - name: Install Flatpak - Boxes
    community.general.flatpak:
      name: org.gnome.Boxes

  - name: Install Flatpak - Thunderbird
    community.general.flatpak:
      name: org.mozilla.Thunderbird

  - name: Install Flatpakl - Kdenlivev
    community.general.flatpak:
      name: org.kde.kdenlive

  - name: Install Flatpak - dconf Editor
    community.general.flatpak:
      name: ca.desrt.dconf-editor

  - name: Set Bashrc file
    ansible.builtin.copy:
      src: files/bashrc
      dest: /home/derek/.bashrc
      owner: derek
      group: derek
      mode: u=rw,g=r,o=r
      follow: yes

  - name: Allow Hibernate in Gnome Menu
    ansible.builtin.copy:
      src: files/com.ubuntu.enable-hibernate.pkla
      dest: /etc/polkit-1/localauthority/50-local.d/com.ubuntu.enable-hibernate.pkla
      owner: root
      group: root
      mode: u=rw,g=r,o=r


  - include_tasks: configs/ubuntu-config.yml
