---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Remove Thunderbird
    ansible.builtin.apt:
      name: thunderbird
      state: absent

  - name: Enable i386 architecture
    command: dpkg --add-architecture i386

  - name: Install Ubuntu Packages
    package:
      name:
        - gnome-software
        - gnome-software-plugin-flatpak
        - steam
        - tmux
        - vim-nox

  - name: Install Snaps
    community.general.snap:
      name:
        - bitwarden
        - chromium
        - htop
        - launcher-ot-minecraft
        - nvtop
        - thunderbird
        - pdfarranger

  - include_tasks: flatpak/flatpak-setup.yml

  - include_tasks: apps/displaylink-setup.yml

  - name: Install Flatpaks
    community.general.flatpak:
      name: net.davidotek.pupgui2

  - name: Set Bashrc file
    ansible.builtin.copy:
      src: files/bashrc
      dest: /home/derek/.bashrc
      owner: derek
      group: derek
      mode: u=rw,g=r,o=r
      follow: yes
