---
- name: Enable screen lock
  become_user: derek
  dconf:
    key: '/org/gnome/desktop/screensaver/lock-enabled'
    value: 'true'

- name: Enable Dark Mode
  become_user: derek
  dconf:
    key: '/org/gnome/desktop/interface/color-scheme'
    value: "'prefer-dark'"
