---
- name: Enable screen lock
  community.general.dconf:
    key: '/org/gnome/desktop/screensaver/lock-enabled'
    value: 'true'

- name: Enable Dark Mode
  community.general.dconf:
    key: '/org/gnome/desktop/interface/color-scheme'
    value: "'prefer-dark'"
