---
- name: Enable screen lock
  become_user: derek
  dconf:
    key: '/org/gnome/desktop/screensaver/lock-enabled'
    value: 'true'

- name: Enable Lock Delay
  become_user: derek
  dconf:
    key: '/org/gnome/desktop/screensaver/lock-delay'
    value: 'uint32 10'

- name: Enable Idle Delay
  become_user: derek
  dconf:
    key: '/org/gnome/desktop/session/idle-delay'
    value: 'uint32 300'

- name: Enable Show Battery Percentage
  become_user: derek
  dconf:
    key: '/org/gnome/desktop/interface/show-battery-percentage'
    value: 'true'


- name: Enable Dark Mode
  become_user: derek
  dconf:
    key: '/org/gnome/desktop/interface/color-scheme'
    value: "'prefer-dark'"

- name: Clock Show Seconds
  become_user: derek
  dconf:
    key: '/org/gnome/desktop/interface/clock-show-seconds'
    value: 'true'

- name: Clock Military Time
  become_user: derek
  dconf:
    key: '/org/gnome/desktop/interface/clock-format'
    value: "'24h'"

- name: Clock Show Weekday
  become_user: derek
  dconf:
    key: '/org/gnome/desktop/interface/clock-show-weekday'
    value: 'true'

- name: Title Bar Options
  become_user: derek
  dconf:
    key: '/org/gnome/desktop/wm/preferences/button-layout'
    value: "':minimize,maximize,close'"
